### ISSUE TITLE
Create a Preset for Backdrop CMS (the Drupal fork)

### ISSUE THREAD

**Issue by jenlampton** [digitalocean/nginxconfig.io#102]
The following PR provides a preset config for Backdrop CMS.

**Comment by 0xB4LINT** [comment]
Hello @jenlampton!
Currently [nginxconfig.io](https://nginxconfig.io) handles the following (most used) PHP based systems: Symfony (+ Laravel), WordPress, Drupal, Magento.
Any other CMS / framework configuration will remain the user's responsibility.

**Comment by fluxsauce** [comment]
Hi there, Backdrop CMS is a fork of Drupal and is PHP based. Does that help clarify? Thanks!
