### ISSUE TITLE
Add support for Nextcloud preset

### ISSUE THREAD

**Issue by asm0dey** [digitalocean/nginxconfig.io#104]
Currently nextcloud requires quite a complex setup:
https://docs.nextcloud.com/server/15/admin_manual/installation/nginx.html

It would be nice to automate setup for it with nginxconfig.io.

**Comment by 0xB4LINT** [comment]
Hello @asm0dey!
Currently nginxconfig.io handles the following (most used) PHP based systems: Symfony (+ Laravel), WordPress, Drupal, Magento.
Any other CMS / framework configuration will remain the user's responsibility.

As far I can see Nextcloud only requires a few additional rules, you can add these to your configuration.

**Comment by asm0dey** [comment]
OK, got it, thanks.
