### ISSUE TITLE
letsencrypt.conf does not included

### ISSUE THREAD

**Issue by boralp** [digitalocean/nginxconfig.io#106]
Web generator does not include /etc/nginx/nginxconfig.io/letsencrypt.conf into the domain's sites-available/*.conf.

**Comment by 0xB4LINT** [comment]
Hello @boralp!
It's included in the HTTP redirection block:
```nginx
# HTTP redirect
server {
	listen 80;
	listen [::]:80;

	server_name .example.com;

	include nginxconfig.io/letsencrypt.conf;

	location / {
		return 301 https://example.com$request_uri;
	}
}
```

The HTTPS block doesn't need that rule.
