### ISSUE TITLE
Certbot command fails to generate correct cert if subdomain has a hyphen 

### ISSUE THREAD

**Issue by acnebs** [digitalocean/nginxconfig.io#113]
This command:

```bash
certbot certonly --webroot -d my-subdomain.example.com --email info@next-api.supernotes.app -w /var/www/_letsencrypt -n --agree-tos --force-renewal
```

generates a SSL cert for "subdomain.example.com", rather than "my-subdomain.example.com". You need to wrap the subdomain in quotes in order for the right cert to be generated, e.g.

```bash
certbot certonly --webroot -d "my-subdomain.example.com" --email info@next-api.supernotes.app -w /var/www/_letsencrypt -n --agree-tos --force-renewal
```

and then it works fine.

This is on Ubuntu 18.04.

**Comment by 0xB4LINT** [comment]
Thanks for the issue!
Is the email parameter fine with the hyphen?

**Comment by acnebs** [comment]
No idea, didn't realize I'd set the email param like that.

**Comment by taliptako** [comment]
This problem reappeared
