### ISSUE TITLE
Wordpress Security.conf Cause Site Problem

### ISSUE THREAD

**Issue by RebelliousWhiz** [digitalocean/nginxconfig.io#114]
**System:** ubuntu 18.04
**Nginx version:** 1.17.3 (also tested on 1.14.0)
**Php version:** 7.3.9 (also tested on php 7.2)
**Wordpress version:** 5.2.3
**Conf link:** https://nginxconfig.io/?0.domain=xxx.xxx.com&0.path=%2Fxxx&0.document_root=&0.ipv6=&0.https=false&0.wordpress&0.php_legacy_routing&php_server=%2Fvar%2Frun%2Fphp%2Fphp7.3-fpm.sock

**Expected:** Wordpress "Site Health" function works fine, the theme editor works fine
**Observed:** Wordpress "Site Health" function not loading, the theme editor not functioning

**What I did:** 
in nginxconfig.io/security.conf
delete `
add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;`

**Result:** everything works as expected.

I am no web pro, so I can't really provide a good suggestion on this...

Please look into this, thanks!

**Comment by mike-sfg** [comment]
If you open the page in Chrome, and look in the Console of Developer Tools (Ctrl-Shift-I on Windows), it will probably tell you what is broken.  It looks like 'unsafe-eval' is required for underscores.min.js to function on that page.

[https://core.trac.wordpress.org/ticket/38695](https://core.trac.wordpress.org/ticket/38695)

**Comment by RebelliousWhiz** [comment]
Thanks for letting me know! That explains.

However, since nginxconfig.io is kinda a tool for noobies like me, maybe it's better to fix this issue whenever people select WordPress as an option?

**Comment by cnZary** [comment]
> If you open the page in Chrome, and look in the Console of Developer Tools (Ctrl-Shift-I on Windows), it will probably tell you what is broken. It looks like 'unsafe-eval' is required for underscores.min.js to function on that page.
> 
> https://core.trac.wordpress.org/ticket/38695

and wp-admin/load-scripts.php also need unsafe-eval

**Comment by MattIPv4** [comment]
The CSP header is a free flow text field on the tool that you can customise as required for situations like this. We will add a warning suggestion beneath the CSP field to notify users of this, but as it is free flow, we cannot automatically update it.

**Comment by MattIPv4** [comment]
https://github.com/digitalocean/nginxconfig.io/commit/9465e8a2fb4be09253b20b56e34274b23853b846
