### ISSUE TITLE
Lost renewing command item

### ISSUE THREAD

**Issue by theaidem** [digitalocean/nginxconfig.io#121]
Just can't see any command there. Is it a bug?
![image](https://user-images.githubusercontent.com/3463974/67481588-103c1600-f684-11e9-9b93-e972ff4f9a9e.png)
Thanks

**Comment by 0xb4lint** [comment]
There's no command #7, it's just a FYI line.

**Comment by eikaramba** [comment]
Very confusing tbh, i still don't understand whether the automatic renewing is already configured or not. currently it does not work for me so i manually added the command from here: https://certbot.eff.org/lets-encrypt/centosrhel7-nginx.html
