### ISSUE TITLE
Yoast SEO issue with `wordpress.conf`

### ISSUE THREAD

**Issue by kb6673** [digitalocean/nginxconfig.io#132]
Yoast SEO is a fairly popular WordPress plugin. I've found the nginxconfig.io breaks the sitemaps on every install I've done.

In `/etc/nginx/nginxconfig.io/wordpress.conf` we could add

```
# WordPress SEO
location = /wp-content/plugins/wordpress-seo/css/main-sitemap.xsl {}
location = /wp-content/plugins/wordpress-seo-premium/css/main-sitemap.xsl {}
```

Above the `# WordPress:` line

**Comment by timscha** [comment]
I can confirm, this helps a lot!

**Comment by TheAlemazing** [comment]
+1 for this

**Comment by MattIPv4** [comment]
I will add the following in, which should handle this in a single line:

```nginx
# WordPress: SEO plugin
location ~* ^/wp-content/plugins/wordpress-seo(?:-premium)?/css/main-sitemap\.xsl$ {}
```

**Comment by kb6673** [comment]
👍
