### ISSUE TITLE
nginxconfig.io is redirected to digitalocean

### ISSUE THREAD

**Issue by jee-r** [digitalocean/nginxconfig.io#133]
Hi,

Currently the site nginxconfig.io is redirected to `https://www.digitalocean.com/community/tools/nginx#?`. Is there a reason for that?

**Comment by jdreesen** [comment]
Maybe because this is a tool from digitalocean? ;)

**Comment by jee-r** [comment]
Ok :/  
The domain name nginxconfig.io was easier to remember and so much classier.
