### ISSUE TITLE
nginxconfig.io is down and not directing to the tool

### ISSUE THREAD

**Issue by poldim** [digitalocean/nginxconfig.io#135]
Using link at the top to https://nginxconfig.io/

![image](https://user-images.githubusercontent.com/16869713/72210523-cdfbc700-3471-11ea-90bb-1c3a274f71a5.png)

https://www.digitalocean.com/community/tools/nginx
![image](https://user-images.githubusercontent.com/16869713/72210532-fa174800-3471-11ea-8be9-eeeba4a9a6dd.png)

**Comment by MaximeMichaud** [comment]
Fix it :'(

**Comment by 0xb4lint** [comment]
Thank you! Fixed.
