### ISSUE TITLE
Wordpress wrong parameter

### ISSUE THREAD

**Issue by MalteKiefer** [digitalocean/nginxconfig.io#138]
Hello,
when I use the generator to create a config for a wordpress site, it looks like this:

```nginx
location / {
		try_files $uri $uri/ /index.php?$query_string;
	}
```
But the nginx config says, it should look like this:

```nginx
location / {
                try_files $uri $uri/ /index.php?$args;
        }
```
https://www.nginx.com/resources/wiki/start/topics/recipes/wordpress/

**Comment by wblondel** [comment]
Hi,

**Comment by wblondel** [comment]
Hi,

The configuration is correct. $args and $query_string are the same.

http://nginx.org/en/docs/http/ngx_http_core_module.html#var_args

> $args
>     arguments in the request line 

> $query_string
>    same as $args

**Comment by MattIPv4** [comment]
As noted above, `$query_string` behaves the same as `$args` and is arguably clearer in what it is doing.
