### ISSUE TITLE
client_max_body_size in URL does not work

### ISSUE THREAD

**Issue by esemeniuc** [digitalocean/nginxconfig.io#139]
Example URL: https://www.digitalocean.com/community/tools/nginx#?0.domain=faxtail.com&0.path=%2Fhome%2Ffaxtail%2F&0.document_root=build&0.cert_type=custom&0.email=hackerhousealpha@gmail.com&0.ssl_certificate=%2Fetc%2Fletsencrypt%2Flive%2Ffaxtail.com%2Ffullchain.pem&0.ssl_certificate_key=%2Fetc%2Fletsencrypt%2Flive%2Ffaxtail.com%2Fprivkey.pem&0.php=false&0.proxy&0.proxy_path=~%20%5E%2F(graphql%7CfileUpload%7CcheckoutOrderApproved%7CpaymentCaptureCompleted%7CfaxStatusCallback)&0.proxy_pass=http:%2F%2Fmitmproxy:8080&0.fallback_html&limit_req&user=nginx&client_max_body_size=25

client_max_body_size should be 25MB, but defaults to 16MB

**Comment by MattIPv4** [comment]
This bug is not present in `master`, which is the branch we are working to maintain and release soon. Closing.
