### ISSUE TITLE
What about OS (Lentos, ubuntu, etc...)

### ISSUE THREAD

**Issue by anvme** [digitalocean/nginxconfig.io#140]
What about os? Different OSs have different paths.

**Comment by MattIPv4** [comment]
Hey @anvme,

Which paths are you saying different between OSes. I'd be more than happy to address this but would some more info on which paths aren't currently customisable in the tool and need changing depending on OS :)

**Comment by bobbyiliev** [comment]
I believe that the paths are the same for most major Linux distributions including CentOS 7 and 8, Fedora, Ubuntu 16/18/20.x and Debian.

The only one that I can think of at the moment that is different is FreeBSD, the Nginx Default configuration file is at: `/usr/local/etc/nginx/nginx.conf`

**Comment by MattIPv4** [comment]
👍 The tool provides an option to manually set this path for the default if needed. I don't think we need anything more complex than that for this.
![image](https://user-images.githubusercontent.com/12371363/93198260-ac5f8780-f744-11ea-9251-9984512a89a2.png)
