### ISSUE TITLE
Step 4 Certbot Commands to Uncomment SSL incorrect with Multiple Sites

### ISSUE THREAD

**Issue by cliffkujala** [digitalocean/nginxconfig.io#143]
Step 4 Certbot Commands to Uncomment SSL incorrect with Multiple Sites is incorrect. The space is left out between the paths to the per website config files.

Step 4 in the Certbot commands with multiple sites produces
sed -i -r 's/#?;#//g' /etc/nginx/sites-available/example.com.conf/etc/nginx/sites-available/example.com.conf

But it should be
sed -i -r 's/#?;#//g' /etc/nginx/sites-available/example.com.conf /etc/nginx/sites-available/example.com.conf

**Comment by MattIPv4** [comment]
cc #136

**Comment by MattIPv4** [comment]
https://github.com/digitalocean/nginxconfig.io/pull/136#issuecomment-637806766
