### ISSUE TITLE
Disable unnecessary HTTP Methods

### ISSUE THREAD

**Issue by SebDanielsson** [digitalocean/nginxconfig.io#144]
Hi,

I read on a NGINX security guide that they recommended disabling unnecessary HTTP Methods.

The recommended config was this:
```
if ($request_method !~ ^(GET|POST|HEAD|PUT)$) {
   return 444;
}
```

Edit: 2020-05-19 Seems like PUT is used by GhostCMS to proposal would be to allow:
GET|POST|HEAD|PUT

Is this something that could be added to security.conf?

**Comment by ihorvorotnov** [comment]
Server tokens are already there, turned off by default:
https://github.com/digitalocean/nginxconfig.io/blob/do/public/templates/conf/nginx.conf.html#L29

**Comment by SebDanielsson** [comment]
Sorry my bad, totally missed that. How about restricting some of the HTTP methods by default?

**Comment by MattIPv4** [comment]
👋 I think this makes sense.

Imo, this should be added as a set of config options per-domain. A set of checkboxes for which HTTP methods you'd like to enable/disable.

**Comment by YasiOnFire** [comment]
Hi. May I try this one?

**Comment by MattIPv4** [comment]
Go for it :)
