### ISSUE TITLE
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

### ISSUE THREAD

**Issue by platipusica** [digitalocean/nginxconfig.io#151]
Hi, 

settings as in #150 

Service does not start due to:

nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

Offending line:

    listen      [::]:80;

This line is written twice since "Redirect subdomains" is checked.

Please advice.

Thanks

**Comment by MattIPv4** [comment]
> This line is written twice since "Redirect subdomains" is checked.

This is correct, the server blocks are bound to different server names.

I believe this issue may lie within your server setup, it seems like NGINX is failing to bind to the IPv6 address. Do you have IPv6 disabled on your system?

**Comment by platipusica** [comment]
Correct, 

disabled v6. 

Not an issue if :: is removed tho.

Thanks!
Closing
