### ISSUE TITLE
updated site's description

### ISSUE THREAD

**Issue by softmarshmallow** [digitalocean/nginxconfig.io#153]
[sudo - permission denied](https://askubuntu.com/questions/230476/how-to-solve-permission-denied-when-using-sudo-with-redirection-in-bash)

when copy base64 string and creating the zip file, on step 1.

some user might face
`-bash: /etc/nginx/nginxconfig.io-my.site.com.tar.gz: Permission denied`

in this case do

```
sudo bash -c "${your-copied-base64-here}"

# i.e
sudo bash -c "echo 'H4sIAGYj6~' | base64 --decode > /etc/nginx/nginxconfig.io-my.site.com.tar.gz"
```

**Comment by softmarshmallow** [comment]
agreed

> I think using `echo 'H4sIAGYj6~' | base64 --decode | tee /etc/nginx/nginxconfig.io-my.site.com.tar.gz > /dev/null` might be safer cross-platform just to avoid the situation where `bash` isn't being used?

**Comment by MattIPv4** [comment]
The fix for this has been deployed :)
