### ISSUE TITLE
gzip: stdin: invalid compressed data--format violated

### ISSUE THREAD

**Issue by softmarshmallow** [digitalocean/nginxconfig.io#154]
copie'd with [config](https://www.digitalocean.com/community/tools/nginx?domains.0.server.domain=209.97.163.230&domains.0.php.php=false&domains.0.reverseProxy.reverseProxy=true&domains.0.routing.root=false)

when,..
`tar -xzvf nginxconfig.io-209.97.163.230.tar.gz`

throws

```
gzip: stdin: invalid compressed data--format violated
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by MattIPv4** [comment]
This is super weird -- I'm unable to reproduce this using the config you linked to when using both the download option as well as the base 64 option.

**Comment by MattIPv4** [comment]
CNR, no other reports, closing.

**Comment by Ghostff** [comment]
Came across this issue while using Windows Terminal. Everything worked fine after switching to the dashboard console, and rebuilding the gzip.
