### ISSUE TITLE
fastcgi_pass php; leads to 'no port in upstream "php"'

### ISSUE THREAD

**Issue by ghbob** [digitalocean/nginxconfig.io#155]
## Information
Issue occurs on <https://www.digitalocean.com/community/tools/nginx>

### Description 
```
# fastcgi settings
fastcgi_pass                  php;
```

is set but no upstream is defined:
`nginx: [emerg] no port in upstream "php" in /etc/nginx/nginxconfig.io/php_fastcgi.conf:8`

However if you add a backup server under Global config > PHP the upstream will defined in `/etc/nginx/nginx.conf`:
```
http {

    upstream php {
        server unix:/var/run/php/php7.2-fpm.sock;
        server unix:/var/run/php5-fpm.sock backup;
    }
```

### Steps to reproduce
e.g. even the default config does not add the socket (currently 7.2): <https://www.digitalocean.com/community/tools/nginx>

```
nginx -t && sudo systemctl reload nginx
nginx: [emerg] no port in upstream "php" in /etc/nginx/nginxconfig.io/php_fastcgi.conf:8
```

### Expected behavior
according to the changes when you add a backup server I guess I'd expect this:
```
http {

    upstream php {
        server unix:/var/run/php/php7.2-fpm.sock;
    }
```

though I just went with: `fastcgi_pass                  unix:/run/php/php7.4-fpm.sock;`

**Comment by MattIPv4** [comment]
Good catch, mistake on my end 🤦  Your fix noted at the end is correct and what the tool should actually be doing. It should only define the upstream when a backup exists, which it does, but when there is no backup it should just set the upstream directly in `fastcgi_pass`.
