### ISSUE TITLE
LetsEncrypt ssl cert paths: /etc/letsencrypt/live instead of /etc/nginx/ssl

### ISSUE THREAD

**Issue by ghbob** [digitalocean/nginxconfig.io#156]
## Details
Results from <https://www.digitalocean.com/community/tools/nginx#?>

### Description 
The generated paths are:
```
    # SSL
    ssl_certificate         /etc/nginx/ssl/example.com.crt;
    ssl_certificate_key     /etc/nginx/ssl/example.com.key;
    ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;
```

however with certbot the paths would look like this:
```
    # SSL
    ssl_certificate         /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;
```

Paths are from Ubuntu 20.04 with certbot 1.5.0 installed via Snap.
However I've used certbot for a while and I am pretty sure this is "always" the path.

### Steps to reproduce
I's the default config.

### Expected behavior
maybe an option to change them or some information about it, it just failed in my case which could be confusing to some.

**Comment by MattIPv4** [comment]
This was also a mistake on my end somewhere along the way in building this, the tool wasn't correctly returning the LE path and was instead falling back to a default. However, I'll also add in an option to change the LE cert root in the global config section.
