### ISSUE TITLE
Port 80 forwards are not site specific in a multisite setup, only the first one will work

### ISSUE THREAD

**Issue by ghbob** [digitalocean/nginxconfig.io#160]
### Description 
For the port 80 to 443 forwards, in the listen 80; block the `server_name` is not added.
Therefore it's a "global" configuration for all sites. When you add multiple sites in the webapp only the first such block in the list will take, all forwards will go to the first site:
```
nginx -t
nginx: [warn] conflicting server name "" on 0.0.0.0:80, ignored
nginx: [warn] conflicting server name "" on [::]:80, ignored
```

### Steps to reproduce
Add two or more sites.

### Expected behavior
If there are more than one site the `server_name` should be added to the forwarding blocks.
Maybe a flag for the "default" site makes sense though for everything else.
e.g. http://example2.com => https://example2.com should obviously work but if http://example.com is configured with a `server_name` as well there is no "catch all" block for port 80 anymore.

### Screenshots
-

**Comment by MattIPv4** [comment]
Good catch, completely missed this rule when porting from Angular to Vue!
