### ISSUE TITLE
add security.txt

### ISSUE THREAD

**Issue by Leptopoda** [digitalocean/nginxconfig.io#167]
### Feature description
Add a configuration option for the security.txt file. It could look like:

```
#security.txt
location /security.txt {
    return 301 http://$host/.well-known/security.txt;
}

location = /.well-known/security.txt {
    alias /<User configurable path>/security.txt
}
```
[Source/ inspired by](https://metahackers.pro/applying-security-txt-in-ghost-nginx/) 

### How the feature is useful
The security.txt is comparable to the robots.txt and serves contact information etc. to security researchers. 
More information can be found on their [site](https://securitytxt.org/).

**Comment by Leptopoda** [comment]
Another option would be to have an option to generate the `security.txt` file too. In this case we could return it as plain text as a 200.

```
#security.txt
location /security.txt {
    return 301 http://$host/.well-known/security.txt;
}

location = /.well-known/security.txt {
    default_type text/plain;
    return 200 '
    Contact: mailto:<example@example.me>
    Preferred-Languages: <some language>
    ';
}
```

The example generator from their website can be found [here](https://github.com/securitytxt/securitytxt.org).

**Comment by MattIPv4** [comment]
👍 I think we should go for the former here, providing an option on each site added for a security.txt path. If present, we then include the blocks in the opening comment for that site.

Whilst nginxconfig is 100% a generator tool, I think we should focus on keeping it aimed at generating nginx config parts, not other files.

**Comment by WilliamChang80** [comment]
Hello, can i work on this issue?

**Comment by MattIPv4** [comment]
Go for it 👍

**Comment by WilliamChang80** [comment]
Should i set the content of security.txt from [here](https://securitytxt.org/) ?

**Comment by Leptopoda** [comment]
Yep this is the official Website of the project.
Keep in mind tahat as said above we don't want a security.txt configurator we want a option to configure where the security.txt lives (see the initial post of this issue)

**Comment by WilliamChang80** [comment]
> Another option would be generate the `security.txt` file as well. In this case we could return it directly as plain text.
> 
> ```
> #security.txt
> location /security.txt {
>     return 301 http://$host/.well-known/security.txt;
> }
> 
> location = /.well-known/security.txt {
>     default_type text/plain;
>     return 200 '
>     Contact: mailto:<example@example.me>
>     Preferred-Languages: <some language>
>     ';
> }
> ```
> 
> The example generator from their website can be found [here](https://github.com/securitytxt/securitytxt.org).

Should i generate the security.txt or just put the detail on the nginx conf file like example above?

**Comment by Leptopoda** [comment]
I guess a config option to point at a file would be enough. See my initial post and the response to it.

Just an input field accepting a file path and putting it into a location rewrite. 

As the standard says the file should be in ` .well-known` but if not possible can also be in the `root` of your website.

Therefore a chexkbox for either the first or the later (or both) would be preferred.
You could add a descriptive text like:
 For a configurator or more information visit the [security-txt website](security-txt.org).

**Comment by WilliamChang80** [comment]
For the content is it enough if i put contact, encryption and preferred languages?

**Comment by MattIPv4** [comment]
👋 If we're going to be generating the contents of the file, we should ensure we're providing all options available in the spec, with best-practice default values.

As I noted above though, we could just provide a single text field and have the user enter a path to their security.txt file as an alternative if we don't want to build a full generator tab.

**Comment by WilliamChang80** [comment]
Currently im on my to finishing the generator but i have no idea where to put the field, is it okay to put it on global config/security tab?

**Comment by MattIPv4** [comment]
If you're going for the single user path field, yeah, security tab works.

If you're building out a full security.txt generator, create a new tab probably, imo.

**Comment by MattIPv4** [comment]
Merged & deployed in prod. Ty all
