### ISSUE TITLE
Empty pid field still has 'pid ;' in the config

### ISSUE THREAD

**Issue by Leptopoda** [digitalocean/nginxconfig.io#168]
### Problem
Originally I wanted to post this as a bugreport but I'm not that shure if this behaviour is intentional or not.

### Description 

When I remove the content of the pid field (https://www.digitalocean.com/community/tools/nginx?global.nginx.pid=) the generated config still has the paid field but just empty. 
```
user                 www-data;
pid;
worker_processes     auto;
```

### Steps to reproduce

Its not a UI bug more like a system bug. Go to the above [link](https://www.digitalocean.com/community/tools/nginx?global.nginx.pid=) or just remove the contents of the pid field.

### Expected behavior

I would like the pid field to be entirely missing or commented.
(I use arch Linux and nginx throws an error because its duplicate or something? Idk but its fixed for me by removing the line). The example config in the [arch wiki](https://wiki.archlinux.org/index.php/Nginx#Configuration) doesn't have the pid specified either.

The same behaviour of leaving a field empty/removing it applies to many other fields (user...) so maybe in such a case the default value should be used as it is still displayed grey in the field? Or the input of the user should be followed and the line removed (maybe with a warning).

**Comment by MattIPv4** [comment]
👍 Good catch, looks like a bug to me. If the user removes the pid, we should assume they want no pid and should remove it from the config completely.

**Comment by Leptopoda** [comment]
As it's closed an the fix is in production can we close this now @MattIPv4 ?

**Comment by MattIPv4** [comment]
Had assumed GitHub auto-closed this. Yup, in prod and should be working 👍
