### ISSUE TITLE
Support for hidden services

### ISSUE THREAD

**Issue by h0ek** [digitalocean/nginxconfig.io#188]
### Feature description
Support for hidden services. Onion domains in Tor network.

### How the feature is useful
Support for Tor network, and allow users to create websites with better privacy for visitors.

Would be cool to add option to implement Onion Location. This option let know visitors that onion address is available for the website.
https://community.torproject.org/onion-services/advanced/onion-location/

It is just a one line in the website conf:
`add_header Onion-Location http://<your-onion-address>.onion$request_uri;`

And also general nginx generator for hidden services.
https://2019.www.torproject.org/docs/tor-onion-service.html.en

For users who would like to create website as hidden service with best security setup.

**Comment by MattIPv4** [comment]
Seems simple enough, will add a new onion tab in the domain configuration section and an option for the onion location in there :)

**Comment by h0ek** [comment]
Awesome, if you need any help or some additional info about hidden services configuration or onion location, let me know I am happy to assist.
