### ISSUE TITLE
Invalid Strict-Transport-Security header format

### ISSUE THREAD

**Issue by etam** [digitalocean/nginxconfig.io#195]
## Information
https://www.whatismybrowser.com/w/TBE3S8L
(for some reason it says I have Javascript disabled, which is not the case)

### Description 
By default Strict-Transport-Security header is defined in `security.conf` and there it's correct.
But when it is moved to site config, it looks like this:
```
add_header Strict-Transport-Security '"max-age=31536000; includeSubDomains" always';
```
Note the single quotes around whole value.

### Steps to reproduce

1. add a second site
2. disable https on this second site

### Expected behavior
It should be
```
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
```

**Comment by MattIPv4** [comment]
Nice catch!
