### ISSUE TITLE
Cannot see config from localhost

### ISSUE THREAD

**Issue by dantheman0207** [digitalocean/nginxconfig.io#225]
## Information

https://whatismybrowser.com/w/Q3N5RFA

## Help request
Unable to see the config website.
### Problem

When I run `npm run dev` I get a correct output. When I visit `http://localhost:8080` I see only the text "2021"
### What I have tried

I can briefly see the website being loaded but then it is covered up.
### Screenshots

![Screenshot 2021-02-16 at 10 39 12 (2)](https://user-images.githubusercontent.com/1239724/108045056-510f2980-7043-11eb-8ce1-b14c060543e3.png)

**Comment by MattIPv4** [comment]
Actually noticed this myself yesterday -- this is due to a `document.write` being used in the Community website that we use as a template. I have a PR open upstream which hopefully should be merged/deployed today.

**Comment by dantheman0207** [comment]
Thanks for the update. I pulled the latest version and did `npm ci` but am still having this issue.

**Comment by MattIPv4** [comment]
Ah yeah, apologies, this fix hasn't gone out yet upstream -- we're planning to deploy today 🤞

**Comment by MattIPv4** [comment]
Fix has been shipped upstream
