### ISSUE TITLE
[Proposal] Set up the php server per site

### ISSUE THREAD

**Issue by Atiladanvi** [digitalocean/nginxconfig.io#227]
## Feature request
Set up the php server (version) per site.

### How the feature is useful
The users will be able to config php server (version) per site.

**Comment by MattIPv4** [comment]
I like this idea and definitely think it could be useful in some cases -- as we don't want to ship breaking changes to the tool wherever possible, I wonder if the best thing to do would be to add a checkbox under the global PHP section for `Define specific PHP server for each site`, and this then allows the PHP server to be set in each website under their respective PHP tabs?

**Comment by Atiladanvi** [comment]
The best way for me is add this config in site section not in global couse is will don't  be global config. If it's were possible we can keep more cohesion in the implementation. the consequence of that would be remove php tab in global section.  Is that acceptable, yes or no?

**Comment by MattIPv4** [comment]
If it is removed from the global config section, backwards compatibility logic will need to be added to ensure that this isn't a breaking change for existing configurations.

I'm happy with either approach, either having it be global by default with an option to make it site-specific, or having it only be site-specific with backwards compatibility logic.

**Comment by Atiladanvi** [comment]
Are you can create a branch for this ? I vote in per site approach

**Comment by MattIPv4** [comment]
I can add this to our backlog to take a look at in the coming weeks, or someone else is welcome to work on it if they'd like (just say before you do, so we don't also start working on it ourselves) :)

**Comment by Atiladanvi** [comment]
:rocket: **Nice ! Great ! Wonderful !** :rocket:
I can try that, I guess.
Put config in:
`/etc/nginx/sites-available/example.com.conf`
```nginx # handle .php
    location ~ \.php$ {
        include nginxconfig.io/php_fastcgi.conf;
        fastcgi_pass unix:<php-server>; 
    }
```
Remove config from:
`/etc/nginx/nginxconfig.io/php_fastcgi.conf`

```nginx # fastcgi settings
fastcgi_pass  unix:<php-server>;
```
Theres another point to change in your opinion ? 
By the way, I'm not sure if this will work for all php servers.
It would help us if we got a automation test to describe a server tests :sweat_smile:.

**Comment by MattIPv4** [comment]
Yeah, that's the premise of the config generation change needed. There will also need to be the relevant changes made to the tool UI, and the logic added to handle backwards compatibility with existing configuration URLs. I'm happy to take a look at it if you'd prefer :)

**Comment by Atiladanvi** [comment]
I've been thinking that maybe we can keep the global php config and add a conditional option into global/persite config. What do you think about this ?
Proposal:
![Captura de tela de 2021-02-18 12-22-22](https://user-images.githubusercontent.com/11599205/108378702-04168900-71e4-11eb-9fc8-a5616d65554b.png)
![Captura de tela de 2021-02-18 12-19-05](https://user-images.githubusercontent.com/11599205/108378705-04af1f80-71e4-11eb-93fb-86dcafad06fe.png)
![Captura de tela de 2021-02-18 12-17-40](https://user-images.githubusercontent.com/11599205/108378710-04af1f80-71e4-11eb-98e7-974c91e2014b.png)

**Comment by MattIPv4** [comment]
I think this is probably quite a confusing UI/UX for users, providing identical configuration options in both per-site configurations and global configurations, and likely will trip us up in the future when maintaining this.

As we already have the rules for PHP set per-site, I think the simplest solution is to move the PHP server config to be per-site and adding the backwards compatibility logic for old config URLs. I'm happy to work on this if you'd prefer :)

We should also do the same for Python at the same time to be consistent as that also has a server configuration option that is currently global.

**Comment by Atiladanvi** [comment]
We share the same concerns. Is confused for user and maintainers :grimacing: . So we will remove tabs in global config. Give me a chance to do that in this weekend ? I would be very happy if you give me just a chance.  :pray:

**Comment by MattIPv4** [comment]
Yeah, go for it! :)

**Comment by Atiladanvi** [comment]
I would like to make some additional remarks:
Maybe we have to change the php path helper. Actually it build the upstream with a key unique: `php`.
```nginx
upstream php {
  server unix:/var/run/php5-fpm.sock;
  server unix:/var/run/hhvm/sock backup;
}
```
To keep the version compatibility we have to build groups of upstreams. Something like this: 

```nginx
upstream php_example_com {
  server unix:/var/run/php8-fpm.sock;
  server unix:/var/run/php8-fpm.sock;
}
upstream php_example2_com {
  server unix:/var/run/php5-fpm.sock;
  server unix:/var/run/php5-fpm.sock;
}
```

We can change the signature of php_path helper to `(domain,  backup = false)` and php_fastcgi.conf to `(domains, domain)`:

[Here](https://github.com/digitalocean/nginxconfig.io/blob/4cfdcdb8d1c2df185e9ba437ca9c79e7c2ef17e8/src/nginxconfig/generators/conf/nginx.conf.js#L53) Then we will be able to do this:
```javascript
domains.forEach(domain => {
  if (domain.php.phpBackupServer.computed){
    config.http.push([ `upstream php_${domain.server.domain.computed.replace('.', '_')}`, {
        server: [
            phpPath(domain),
            `${phpPath(domain, true)} backup`,
        ],
    }]);
  }
})
```
**One more thing:**
The logic to add handle backwards compatibility change only those files below ?
`backwards_compatibility.js` and `import_data.js`.

I will submit a **PR** without this change, because i'am not able to know how make this exactly. But if you can explain for me how it works or the way to do, i can push it too. I knowl'll have to write something to do this:

```javascript
if(data.global.php.phpServer)  domainImported.php.phpServer = data.global.php.phpServer;
if(data.global.php.phpServerCustom)  domainImported.php.phpServerCustom = data.global.php.phpServerCustom;
if(data.global.php.phpBackupServer)  domainImported.php.phpBackupServer = data.global.php.phpBackupServer;
if(data.global.php.phpBackupServerCustom)  domainImported.php.phpBackupServerCustom = data.global.php.phpBackupServerCustom;
```
But how and where ? 
Maybe after this [line](https://github.com/digitalocean/nginxconfig.io/blob/4cfdcdb8d1c2df185e9ba437ca9c79e7c2ef17e8/src/nginxconfig/util/import_data.js#L104)

**Comment by MattIPv4** [comment]
I've left some feedback around this in the PR itself :)

**Comment by Atiladanvi** [comment]
Now we can define specific PHP server for each site. See: #232
