### ISSUE TITLE
Syntax highlighting doesn't work.

### ISSUE THREAD

**Issue by Atiladanvi** [digitalocean/nginxconfig.io#235]
## Information
Browser details https://whatismybrowser.com/w/G93E9TN
## Details
After any input changes the **highlights** doesn't work.
### Description 
Well, that's because there is something wrong with  `Prism.util.isActive ` function.
### Steps to reproduce
Just change any input.
### Expected behavior
Highlight the changes.
### Screenshots
![image](https://user-images.githubusercontent.com/11599205/109037764-d9c44000-76a9-11eb-959f-68971f9cced5.png)

**Comment by MattIPv4** [comment]
Cannot reproduce in production, looks to be an issue in dev only. I wonder if some globals are being registered badly due to hot reloading.

**Comment by Atiladanvi** [comment]
That's probably what it is. I run the app component out of the our build workflow and works perfectly.
