### ISSUE TITLE
SSL directive is deprecated

### ISSUE THREAD

**Issue by paulwaldmann** [digitalocean/nginxconfig.io#256]
### Description 
The "ssl" directive is deprecated, use the "listen ... ssl" directive instead.

### Steps to reproduce
All generated nginx.conf will encounter this warning.

### Expected behavior
No warning should be returned when reloading nginx.

### Screenshots
![ssl](https://user-images.githubusercontent.com/32001342/116611593-d746c680-a936-11eb-901f-8607b8b8d305.PNG)

**Comment by MattIPv4** [comment]
👋 This is intentional behaviour in the tool -- we utilise the SSL directive to ensure that SSL is disabled on all versions of NGINX whilst certbot is configured. Subsequent setup steps in the nginxconfig UI will instruct you to run another sed command that will remove the SSL directive again.

**Comment by paulwaldmann** [comment]
Oops, apologies! Better safe than sorry 😅
