### ISSUE TITLE
The generated config files permission are too open

### ISSUE THREAD

**Issue by sixg0000d** [digitalocean/nginxconfig.io#257]
### Feature description

The generated and installed config files permission are too open, any user logined on the system can read and write them. So i suggest append a `chmod` command into **Extract tar step** to keep config files more safty.

### How the feature is useful

like:

```bash
tar -xzvf nginxconfig.io-example.com.tar.gz | xargs chmod 0644
```

the `tar xzvf` command will return which files it extracted, and then we can use xargs to convert them as arguments to `chmod` command.

**Comment by MattIPv4** [comment]
#299
