### ISSUE TITLE
why doesn't it work when the home page switches to the native language

### ISSUE THREAD

**Issue by killersteps** [digitalocean/nginxconfig.io#262]
Why doesn't it work when the home page switches to the native language
example:
https://www.digitalocean.com/community/tools/nginx?global.app.lang=zhCN
will be automatically redirected to
https://www.digitalocean.com/community/tools/nginx
native language configuration does not work
look forward to the answer,thank u

**Comment by MattIPv4** [comment]
👋 I believe this was the same issue as reported in #265, which has now been fixed. Let me know if not.
