### ISSUE TITLE
Language packs not loading

### ISSUE THREAD

**Issue by liangyao375** [digitalocean/nginxconfig.io#265]
## Information

N/A

### Description 

Language packs not loading when selected in the language dropdown.

### Steps to reproduce

Load tool on the DigitalOcean site, select a language pack from the dropdown.

### Expected behavior

Language pack loads.

### Screenshots

N/A

**Comment by MattIPv4** [comment]
Thanks for the report @liangyao375 -- the fix for this should be live very shortly 👍
