### ISSUE TITLE
Add Forwarded Header

### ISSUE THREAD

**Issue by jcgoette** [digitalocean/nginxconfig.io#270]
## Feature request
Add Forwarded Header

### Feature description

https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

Perhaps with user-selected option on how to handle [coexistence with X-Forwarded-*](https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/#coexistence-with-x-forwarded)?

### How the feature is useful
Adds the currently NGINX recommended, _partial_ implementation of RFC 7239 standardized Forwarded header

Understandable if not wanting to implement _partial_ solution... also, I don't mind taking a stab at it with PR.

**Comment by MattIPv4** [comment]
👍 Always open to adding more options as long as they have sensible default values and easy to understand/configurable options for the user. You're most welcome to create a PR if you want!
