### ISSUE TITLE
Missing Analyze Script

### ISSUE THREAD

**Issue by jcgoette** [digitalocean/nginxconfig.io#271]
### Problem
There is no `analyze` script in `package.json` per [README](https://github.com/jcgoette/nginxconfig.io#%EF%B8%8F-development):

- `npm run analyze`

**Comment by MattIPv4** [comment]
👋 Nice catch --  The analyze script was removed in https://github.com/digitalocean/nginxconfig.io/pull/267 as bundle analysis is now run automatically on every build. Feel free to create a quick PR to update the README :)
