### ISSUE TITLE
Permissions-Policy Header (or disable FloC checkbox)

### ISSUE THREAD

**Issue by WalshyDev** [digitalocean/nginxconfig.io#281]
### Feature description
Implement a way to create a `Permissions-Policy` header. Available options here: https://github.com/w3c/webappsec-permissions-policy/blob/main/features.md

I'm not sure how the UI for this would actually look, it isn't as simple as checkboxes or whatever. It would maybe be an idea to just use a text input like CSP (by the way, can we link to a CSP builder like Report URI's - https://report-uri.com/home/generate).

Permissions Policy is still a draft but already is having usage (FloC for example). It isn't super supported currently (https://caniuse.com/permissions-policy), the old way of doing this is more supported (https://caniuse.com/feature-policy).

I don't think it makes too much sense to implement it currently as there's still quite a few things to figure out (For example, you cannot by default deny or allow everything ([ref](https://github.com/w3c/webappsec-permissions-policy/issues/189))).
**However!** I think maybe just adding a checkbox for now to disable FloC (`Permissions-Policy: interest-cohort=()`), I would be down to PR this if you want that.

### How the feature is useful
The Permissions-Policy header can massively improve security, this combined with CSP means that any injected JS cannot do bad things. If it did beat CSP (maybe a third party is compromised) then this header can prevent the JS doing things like tracking users, reading the clipboard, etc.

Or, for now, a checkbox to disable FloC tracking on the users site (only applies if it detects ads or it accesses Floc API). This is a simple header addition. More info on https://amifloced.com/

**Comment by MattIPv4** [comment]
I agree that building out a full UI for this would likely be beyond the scope of the tool here -- a text input that the user can customise seems like the better option to be consistent with CSP and not result in scope creep for the project.

As nginxconfig is all about providing the best set of defaults possible, I'd be quite happy with having `interest-cohort=()` as the default value for this new input/header, and then simply letting the user remove that if they'd prefer to have FLoC enabled. I don't think we need to add a dedicated checkbox as we'd then open up the tool to more checkboxes to configure the header etc. which I want to avoid.

**Comment by WalshyDev** [comment]
Fair enough, do you think it's a valid thing to add while in it's current state?
