### ISSUE TITLE
Cache-Control immutable

### ISSUE THREAD

**Issue by denji** [digitalocean/nginxconfig.io#33]
* https://code.facebook.com/posts/557147474482256/this-browser-tweak-saved-60-of-requests-to-facebook/
* https://bitsup.blogspot.com/2016/05/cache-control-immutable.html
  - https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/
* https://www.keycdn.com/blog/cache-control-immutable
* https://blog.fortrabbit.com/mastering-http-caching

### Browser Support
* __Firefox__ - supported since [Firefox 49](https://bugzilla.mozilla.org/show_bug.cgi?id=1267474)
* __Microsoft Edge__ - supported since [Edge 15](https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/17168363-support-chrome-s-improved-reload-behavior-or-cache)
* __Chrome__ - Not supported as [Chrome already has a feature implemented that prevents subresource revalidation on reload](https://bugs.chromium.org/p/chromium/issues/detail?id=611416)
* __Safari__ - Supported in [Safari Technology Preview 24](https://bugs.webkit.org/show_bug.cgi?id=167497)

```nginx
# add_header Cache-Control "public,max-age=3600,immutable";
# add_header Cache-Control "public,max-age=604800,immutable";
# add_header Cache-Control "public,max-age=31536000,immutable";
````

**Comment by MattIPv4** [comment]
Hey @denji, 

Do you have any suggestions for exactly which rules within the generated configs would benefit from being set to be immutable?
