### ISSUE TITLE
[warn] the "ssl" directive is deprecated, use the "listen ... ssl"

### ISSUE THREAD

**Issue by PontusTideman** [digitalocean/nginxconfig.io#333]
### Description 
Putting up a new VPS with nginx 1.18 and the confs fails due to [warn] the "ssl" directive is deprecated, use the "listen ... ssl". 

```
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/sites-enabled/somedomain.TLD.conf:2
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/sites-enabled/somedomain.TLD.conf:42
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/sites-enabled/somedomain.TLD.conf:56
```

### Steps to reproduce
Create a new config, and when you paste the first line to fix the SSL, that oneliner will mess it up because it adds outdated stuffs to the configs.

https://futurestud.io/tutorials/nginx-how-to-fix-ssl-directive-is-deprecated-use-listen-ssl

### Expected behavior
The form needs to be fixed to solve this, until then you need to manually go in and fix it by your self!

**Comment by MattIPv4** [comment]
No response, closing. This intentional behaviour that is temporary during the setup steps and emits a warning, not a failure.

**Comment by klevvit** [comment]
Hi! Now it became a problem for me: `[emerg] 11883#11883: unknown directive "ssl"`

```
nginx version: nginx/1.25.3
built with OpenSSL 3.1.3 19 Sep 2023 (running with OpenSSL 3.1.4 24 Oct 2023)
TLS SNI support enabled
```

**Comment by MattIPv4** [comment]
👋 @klevvit Would you mind filing a new issue capturing the fact this is now resulting in an NGINX failure? I imagine more recent versions have now completely dropped support, so we'll probably have to drop the backwards compatibility and remove this directive.

**Comment by klevvit** [comment]
> 👋 @klevvit Would you mind filing a new issue capturing the fact this is now resulting in an NGINX failure?

Done! #458
