### ISSUE TITLE
access.log and error.log placement

### ISSUE THREAD

**Issue by SorinGFS** [digitalocean/nginxconfig.io#354]
## Feature request

Place the `access_log` and  `error_log` directives inside the main server block instead of http block.

### Feature description

Disable `access_log` at http block:
**File:** /etc/nginx/nginx.conf
```nginx
# ...
http {
    # ...
    access_log off;
    # ...
}
# ...
```

Enable per site `access_log` and  `error_log` at main server block:
**File:** /etc/nginx/sites-available/example.com.conf
```nginx
server {
    listen                  443 ssl http2;
    listen                  [::]:443 ssl http2;
    server_name             example.com;
    set                     $base /var/www/example.com;
    root                    $base/public;
    # new lines here
    error_log               /var/log/nginx/${server_name}_error.log warn;
    access_log              /var/log/nginx/${server_name}_access.log buffer=512k flush=1m;;
    # ...
}
# ...
```
**Note:** the `${server_name}` variable must be replaced with the actual `server_name` set by the user for current website since Nginx does not accept variables in `error_log` or `access_log` directives path.

### How the feature is useful

Every site has from 3 to 5 server blocks for 301 redirects, this means that  `access_log` will be filled with useless info. Disabling  `access_log` at http level and enabling only for the main server block will ensure cleaner logs. Also, enabling per site  `access_log` will allow a faster i/o (smaller files) and faster spotting of entries (for example using bash tail will retreive only the records belonging to a certain site). The last two arguments  `buffer=512k flush=1m` will massively reduce the i/o frequency by keeping the records in memory up to 512Kb or dumping them to file after 1 minute  (in case of not reaching the limit). Enabling per site `access_log` can also be made optional (for backward compatibility, or for user preference) by enabling the `${server_name}_` part from syntax only when a checkbox is checked. IMHO it should be enabled by default, but any case is better than before.

**Comment by MattIPv4** [comment]
Sure :)

**Comment by 201B153** [comment]
> Sure :)

ok, thanks.

**Comment by SorinGFS** [comment]
> I there anything wrong or else to do..?

I don't see anything about personalizing `accessLog` and `errorLog` filenames by adding `${server_name}` in them, and nothing about `accessLog` parameters `buffer=512k flush=1m` like here:

```shell
    error_log               /var/log/nginx/${server_name}_error.log warn;
    access_log              /var/log/nginx/${server_name}_access.log buffer=512k flush=1m;
```

Splitting logs by `server_name` will allow us to analize logs with ease, log analisers can load those files much faster, especially when we talk about months of logs. `Nginx` log folder will look like this:

```shell
domain.com_access.log
domain.com_error.log
other.net_access.log
other.net_error.log
so on...
```

The `accessLog` parameters are also very important. When `nginx` receives a request it fills the logs in real time, and this can be a problem on servers with high traffic. Using `buffer=512k flush=1m` parameters instructs `nginx` to keep the records in memory and dump them into the file after 1 minute, or if bigger than 512kb. This values are tested and can be hardcoded, but for brevity you can also think some inputs to allow the user to set their own values for `buffer` and `flush`. IMHO this would be to much, those defaults are ok.

**Comment by 201B153** [comment]
>  IMHO this would be to much, those defaults are ok.

means can I PR with the above code or add anything else? 
I don't think this is my level of code another way.😓

**Comment by MattIPv4** [comment]
+1 to what Sorin has noted here -- now that these files are within the server blocks, we'll want to move these from being globally configurable file names to being per-server file names. And I'd agree that being able to customise buffer/flush alongside the file names makes sense.

**Comment by 201B153** [comment]
> +1 to what Sorin has noted here -- now that these files are within the server blocks, we'll want to move these from being globally configurable file names to being per-server file names. And I'd agree that being able to customise buffer/flush alongside the file names makes sense.

So is the issue not available any more?

**Comment by MattIPv4** [comment]
I don't follow what you're asking -- you asked to have this issue assigned to you so **you** could work on it?

**Comment by MattIPv4** [comment]
What Sorin and I have noted here should be included in the work for solving this issue.

**Comment by SorinGFS** [comment]
@MattIPv4 

I saw the new PR and I think the work is going in the right direction. Still, there are some things missing:

1. in `nginx.conf` at `http` level `access_log off;` This should be always off, even if user doesn't choose to customize `access_log` filename. This setting would disable `access_log` globally, and user will enable it at server level.
2. in `nginx.conf` at `http` level `error_log              /var/log/nginx/error.log warn;` can be removed since that is the `nginx` default setting. Moreover, if someone opts to cusomize `error_log` filename in a custom `nginx` compilation this setting would cancel that customization.

**Comment by MattIPv4** [comment]
I don't follow why removing the ability to set the access log globally is beneficial? What if a user just wants to enable access logging for everything, and not worry about having to enable it for each and ever server they have configured. Removing the global option seems like it just makes the user experience worse...

I also disagree with removing the default error log, and your justification for it. If someone is using custom nginx compilation, that is on them to realise that might collide with their own configurations they're using from this tool. They can just as easily change the error log name here.

**Comment by SorinGFS** [comment]
@MattIPv4 

> I don't follow why removing the ability to set the access log globally is beneficial? What if a user just wants to enable access logging for everything, and not worry about having to enable it for each and ever server they have configured. Removing the global option seems like it just makes the user experience worse...

If user wants to enable access log globally this could be another checkbox in logging tab. Having access log off globally was my starting point in this issue:
> Every site has from 3 to 5 server blocks for 301 redirects, this means that access_log will be filled with useless info. Disabling access_log at http level and enabling only for the main server block will ensure cleaner logs.
When an user adds a new website it doesn't have control over those server blocks via interface, so I think access log off globally is a smarter solution. I use this for ages now, and performance impact is high, logs are also cleaner. 

For second part:
> I also disagree with removing the default error log, and your justification for it. If someone is using custom nginx compilation, **that is on them to realise that might collide with their own configurations they're using from this tool.** They can just as easily change the error log name here.

It doesn't colide, it just overwrites the setting he choose to place in `nginx` compilation. Ultimately the setting from `logging` tab will win. Anyway, this error log setting from http level is not that important, but `access_log off;` is! Please think deeply before this decision, do some performance tests if you don't beleave it (of course it requires some high trafic to understand differences).

**Comment by MattIPv4** [comment]
> If user wants to enable access log globally this could be another checkbox in logging tab. 

That is exactly what the PR already contains...

**Comment by SorinGFS** [comment]
> That is exactly what the PR already contains...

If you will take my advice and set `access_log off;` globally what the PR already contains would not enable access logs globally but only in that specific server block, which of course is the desired behaviour, but it wouldn't be globally! Please remember that there are like I said 3 to 5 extra server blocks for redirects, an user may want to enable access logs for those server blocks too (for testing purposes in development mode).

**Comment by MattIPv4** [comment]
The PR contains a new option in the global logging section that allows the user to choose whether `acces_log` is set to `off` or a log path at the global level, as well as options in domain-specific logging sections for the same.

**Comment by SorinGFS** [comment]
When I tested the interface that setting you mention it doesn't set access log off everywhere but only in that specific main server block. The server blocks like the following ones will continue to take their settings from the http level, which now is `access_log /var/log/nginx/access.log;`

```nginx
server {
    listen                  443 ssl http2;
    listen                  [::]:443 ssl http2;
    server_name             *.example.com;

    # SSL
    ssl_certificate         /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;
    return                  301 https://example.com$request_uri;
}

# HTTP redirect
server {
    listen      80;
    listen      [::]:80;
    server_name .example.com;
    include     nginxconfig.io/letsencrypt.conf;

    location / {
        return 301 https://example.com$request_uri;
    }
}
```

This means that logs will filled with 301 redirects uselessly.

**Comment by MattIPv4** [comment]
So what would you expect the global logging option to do when enabled then, if not logging these server blocks?

Would it make more sense if the domain-level logging options had a secondary set of options for the redirect server blocks?

And would it make more sense if the domain-level logging options had "on", "global", or "off", where "global" removes the domain-level `access_log` directive completely so it relies on the global directive in the `http` block?

**Comment by SorinGFS** [comment]
@MattIPv4 

First, at `nginx.conf` http level setting must be `access_log off;`. Always. No question about that, this will allow us to have grnullar control over `access_log` settings inside server blocks. 
Secondly, the settings inside `logging` tab can be like this: option `on` and `off`, and if `on` is selected in addition to those text imputs where user customizes the path should be another checkbox `enable access logs for redirects` (disabled by default). And if user checks this last checkbox the app should put exact same directives inside secondary server blocks (those for redirects)

**Comment by MattIPv4** [comment]
👍 That makes sense to me.

My only concern is that having any of this `off` by default is a breaking change for the tool, as the current default behaviour for any exported configuration is that access logging is enabled globally, to a single file (unless domain-specific logging was enabled).

We need to think about what can be done to map the existing settings to the new ones, and what defaults make sense to maintain as much backwards compatibility to for existing configurations as possible.

Perhaps by default, we'll need to ensure that all `access_log` paths at the domain level are set based on the old `global.logging.accessLog`, unless the `domains.<id>.logging.accessLog` boolean is true then they'd perform the domain substitution on the path. I think having `access_log` on by default for every domain would be for the best, to maintain backwards compatibility, but having the redirect blocks be `off` by default seems like a logical breaking change to make.

---

What's your view on `error_log`, should that still be a global option that can be overridden at the domain level, or should it just be at the domain level as well?

**Comment by MattIPv4** [comment]
cc @kobim as this is your PR essentially being discussed (unsure why the conversation was started here rather than in your PR, but oh well).

**Comment by SorinGFS** [comment]
@MattIPv4 

> I think having `access_log` on by default for every domain would be for the best, to maintain backwards compatibility, but having the redirect blocks be `off` by default seems like a logical breaking change to make.

Totally agree with this.

> What's your view on error_log, should that still be a global option that can be overridden at the domain level, or should it just be at the domain level as well?

As I mentioned earlier I think the `error_log` setting is useless at `nginx.conf` http level, and it should be managed exactly as we plan for `access_log` (inside logging tab). However, there is a difference: `error_log` has no `off` option, it can only be configured using log levels. Therefore, IMHO there is no need to have custom configuration for redirect server blocks, existing `nginx` default would be good enough. And, the setting inside `logging` tab should strictly refer to main server block, allowing user to customize the path and log level.

Once this plan is realised I have one more new idea for logging, but first let's get this done.

Sorry about writing here instead the PR, should we continue there?
