### ISSUE TITLE
MariaDB / MySQL Calculated Column not being imported into BB

### ISSUE THREAD

**Issue by poirazis** [digitalocean/nginxconfig.io#376]
Self Host Dabian, latest

I have added 4 columns to a MariaDB table that i am already using in BB.
one of these 4 columns is a calculated on ( GENERATED ALWAYS AS ... )
I Fetch Tables inside BB.
Out of the 4 new columns i created, only 3 are imported. The calculated column is not.
Is this a bug or expected ?

**Comment by MattIPv4** [comment]
👋 Hey! I'm not sure what exactly you're asking or how this is related to NGINXConfig?

**Comment by poirazis** [comment]
Hey, I am so so sorry! I posted in the wrong Repository !!! 
Deleting now.
