### ISSUE TITLE
Reverse proxy headers "Host"

### ISSUE THREAD

**Issue by mateiandrei94** [digitalocean/nginxconfig.io#382]
## Information
Reverse proxy configuration does not work as expected.

`/etc/nginx/nginxconfig.io/proxy.conf`
contains : `proxy_set_header Host $host;`
this is wrong if my destination is NOT `$host`

Using the UI, in the `Reverse proxy` tab
other than the
- `Reverse proxy` `enable reverse proxy` checkbox
- `path`
- `proxy_pass`
I expect a 4th field which is the HTTP `Host` header value that should be sent along the requests sent to the `proxy_pass` server

=== OR

for `proxy_pass` values that are an `ip:port` value it's ok as it is right now.
however for `proxy_pass` values that are an URL containing a domain name or dns name, i.e.: http or https://example.com/ the `proxy_set_header Host` value should be `$proxy_host` not `$host`
i.e. : `proxy_set_header Host $proxy_host` alternatively the `proxy_set_header Host` should be omitted since $proxy_host is the default value nginx takes.

### Description 
Using the UI, when configuring a reverse proxy with server.domain = `server-proxy.example.com` with `location`=`/` and with `proxy_pass`= URI `https://example.com/` the call to `example.com` is currently made with HTTP `Host` header = `server-proxy.example.com` (i.e.: the `$host` value) it should instead be made with `example.com` as specified in the URI value of `proxy_pass` (i.e.: `$proxy_host`)

As you know, `example.com` will be translated by some DNS server to an `IP` however the server found at that IP might host multiple HTTP servers with different names, it might itself be a reverse proxy. This means that multiple DNS names could resolve to the same IP, however when calling said server with different host names we might get different web services.

When configuring a reverse proxy `website` the UI tool always adds a `proxy_set_header Host $host;` no matter what; this is currently applied to all generated `server.location` objects, this is fine if the `proxy_pass` destination is an `ip:port` kind of server or some other server that ignores the `Host` HTTP header or one that has a default `unknown Host` header handler which is the intended proxy destination.
In any other scenario this will result in an error or will result in a call made to the wrong (or not intended) destination

### Steps to reproduce
Here is an example
https://www.digitalocean.com/community/tools/nginx?domains.0.server.domain=server-proxy.example.com&domains.0.server.documentRoot=&domains.0.https.certType=custom&domains.0.https.sslCertificate=%2Fetc%2Fnginx%2Fssl%2Fgoogle-proxy.com.chain.pem&domains.0.https.sslCertificateKey=%2Fetc%2Fnginx%2Fssl%2Fgoogle-proxy.com.key&domains.0.php.php=false&domains.0.reverseProxy.reverseProxy=true&domains.0.reverseProxy.proxyPass=https%3A%2F%2Fserver.example.com%2F&domains.0.routing.root=false&domains.0.logging.accessLog=true&domains.0.logging.errorLog=true&global.nginx.clientMaxBodySize=50

As you can see, `/etc/nginx/sites-available/server-proxy.example.com.conf` contains
```
    # reverse proxy
    location / {
        proxy_pass https://server.example.com/;
        include    nginxconfig.io/proxy.conf;
    }
```
which `include nginxconfig.io/proxy.conf;`
and `/etc/nginx/nginxconfig.io/proxy.conf`
contains  `proxy_set_header Host $host;`

Using `nginx version: nginx/1.18.0` (I suppose all the other versions behave the same);
in this scenario the `$host` variable expands to `server-proxy.example.com`
This means that the call to `https://server.example.com/` will be made with HTTP `Host` header value `server-proxy.example.com` which is not the intended destination since the value in the UI was set to `server.example.com`

### Expected behavior
I expect the nginx configuration to use the correct `Host` header value when calling the `proxy_pass` destination depending on whether the UI `proxy_pass` value contains a host name or an `ip:port`.

### Screenshots
No need

### Best course of action
In the UI simply add a 4th optional field in the `Reverse proxy` tab.
Name it `proxy_pass Host` or something similar.
If the field does not have a value behave as it does right now.
If the field does have a value do this:

```
    # reverse proxy
    location / {
        proxy_pass https://server.example.com/;
        proxy_set_header Host ******replace here proxy_pass Host as set in the UI******;
        include    nginxconfig.io/proxy-ho-host.conf;
    }
```

where the file `nginxconfig.io/proxy-ho-host.conf` is the same as `nginxconfig.io/proxy.conf` except that it does NOT contain a `proxy_set_header Host $host;` line

**Comment by MattIPv4** [comment]
👋 Passing through the original host is relatively standard proxy behaviour (see: Cloudflare).

I agree that it'd be nice to have an option to change this though, a new optional `Proxy host header override` text field under the `Reverse proxy` tab should suffice. If set, the `proxy_set_header Host` directive will be set to the given host, otherwise it will retain the default `$host` value.

And yes, the `proxy_set_header Host` directive would need to move from `proxy.conf` to the site-specific conf instead.

**Comment by mateiandrei94** [comment]
I agree with You that there is a "relatively standard proxy behaviour", however, I find myself in a situation where I need the `Host` header to reflect the `proxy_pass` host name.
Currently, after generating the config, I'm editing it manually, this is a chore.

Adding a 4th `optional` field in the `Reverse proxy` tab `IS` backwards compatible, it would not "break" older configs. This means that anyone with `old` configurations will not have any issues re-generating them and getting the same output except for, as You say the `proxy_set_header Host` directive which would need to move from proxy.conf to the site-specific conf, however the value will be the same if the new `4th field is empty`.

With this "patch" anyone that needs a custom "Host" as I do, can simply set one using the UI.

P.S.:
I'm a programmer, I could write a "patch" myself, that adds the 4th field I'm talking about,
I would like to ask: If I take the time to do it, do You think it would be accepted and perhaps pushed on digitalocean.com ? or would I be wasting my time.

As you know, time is money :)

Thanks.

**Comment by MattIPv4** [comment]
Yup, would be more than happy to accept a PR that implements what you suggested and I outlined above :)

**Comment by MrJmpl3** [comment]
Hello, I return to the project to do my Hacktoberfest 2022 😁

The idea to PR is:
- Make 'Proxy host header override' field in 'Reverse proxy' tab
- If set, Move 'proxy_set_header Host' to specific server with the data of the field

Is correct?

**Comment by MattIPv4** [comment]
Hey! Yah, I think we could probably just move `proxy_set_header` to the specific server always (to avoid extra logic in the conf generators), and just switch between `$host` and the override value.
