### ISSUE TITLE
undefined running the app locally

### ISSUE THREAD

**Issue by treboryx** [digitalocean/nginxconfig.io#385]
I followed the steps line by line running this locally from the README file and I get the following on my screen:
![image](https://user-images.githubusercontent.com/5408097/193410629-6d0b90b2-1451-4475-a398-f11c74b8bae7.png)

Steps:
- git clone
- npm ci
- npm run dev

node version: 16.17.1

**Comment by MattIPv4** [comment]
👋 This is a known bug with some of our dev tooling that I hope to tackle next week, sorry about that!

As a workaround for now, update the `"build:template": "do-vue template && node src/nginxconfig/build/template.js",` line in `package.json` to be `"build:template": "BLANK_TEMPLATE=true do-vue template && node src/nginxconfig/build/template.js"`
