### ISSUE TITLE
Add an auto_assign github action

### ISSUE THREAD

**Issue by Johnnyteck** [digitalocean/nginxconfig.io#390]
### Feature description

 Add an auto_assign github action
### How the feature is useful

This action helps to automatically assign reviewers to pull requests (such way, they get notified) to improve the git workflow and prevent a PR from taking too long to be attended to.

**Comment by MattIPv4** [comment]
I do not see a need for an action like this. As the only maintainer of this repo, I have notifications on for when PRs are raised.

**Comment by Johnnyteck** [comment]
ooh, didn't check that. Thank you
