### ISSUE TITLE
Configuration persistence

### ISSUE THREAD

**Issue by myesn** [digitalocean/nginxconfig.io#397]
### Problem

After I finished configuring the [NGINXConfig](https://www.digitalocean.com/community/tools/nginx) website, I didn't find a button to save it, when I close the page and open it next time, I can't find the last configuration, please ask if there is currently a function to save the previous configuration? If not, will it be supported in the future?

**Comment by MattIPv4** [comment]
The URL in your browser as you change the config is updated to store the current config, so you can just copy the URL.

Under `Global config -> Tools` there is also a `Share URL` field that contains the same URL, and in the files generated there is an `nginxconfig.txt` file that contains the same URL.
