### ISSUE TITLE
npm ci err

### ISSUE THREAD

**Issue by ZhangWeike2000** [digitalocean/nginxconfig.io#407]
node version: v14.21.1
npm version: 9.1.1

Use npm ci OR npm ci --legacy-peer-deps to appear:

![微信截图_20221116235553](https://user-images.githubusercontent.com/54729175/202229580-78655a9f-c209-4263-b99f-f67a947a6be1.png)

**Comment by MattIPv4** [comment]
Please make sure you're using the required versions of Node.js & NPM as specified in the package: https://github.com/digitalocean/nginxconfig.io/blob/e2a95a5ed4d2c32abe7c92e9d94587e8455fcfdf/package.json#L7

**Comment by ZhangWeike2000** [comment]
The installation of the corresponding version started successfully，But there's another problem，After successful startup：
Where is the nginx configuration page???

![微信截图_20221117094302](https://user-images.githubusercontent.com/54729175/202333451-94f7549a-e39d-48f8-8350-ec8b5c7742f5.png)
