### ISSUE TITLE
Not found. Configuration page

### ISSUE THREAD

**Issue by ZhangWeike2000** [digitalocean/nginxconfig.io#408]
The installation of the corresponding version started successfully，But there's another problem，After successful startup：
Where is the nginx configuration page???

![微信截图_20221117095036](https://user-images.githubusercontent.com/54729175/202334362-d144a9a5-fcbb-4f72-8604-cb12ee380411.png)

![微信截图_20221117094302](https://user-images.githubusercontent.com/54729175/202333451-94f7549a-e39d-48f8-8350-ec8b5c7742f5.png)

_Originally posted by @ZhangWeike2000 in https://github.com/digitalocean/nginxconfig.io/issues/407#issuecomment-1317939329_

**Comment by DavidShuYi** [comment]
I have this same problem.

**Comment by SuBaiQiao** [comment]
Is it solved? That's my problem, too

**Comment by MattIPv4** [comment]
Hey folks, are there any errors in the browser console when this happens? Have you tried using WSL rather than running this directly via Windows?

**Comment by sunburst-yz** [comment]
I got error:
`Uncaught (in promise) Error: Cannot find module './de/languages.js'
    at app.js:2083:11
    at async getI18n (setup.js?bfd8:48:1)`
Maybe webpack failed to pack language.js, my environment is:
`
$ node -v
v18.12.1

$ npm -v
8.19.2

$ npm info webpack
webpack@5.75.0 | MIT | deps: 24 | versions: 803
`

**Comment by MattIPv4** [comment]
Ahah! Thank you, that was what I needed. I think this is probably a bug in how we use Webpack loading for the language packs -- will investigate.
