### ISSUE TITLE
Add contributing and code of conduct files.

### ISSUE THREAD

**Issue by theritikchoure** [digitalocean/nginxconfig.io#422]
![image](https://user-images.githubusercontent.com/56495602/221404466-0e9cba40-db84-48bf-8abc-40bfdaffc0de.png)

**Comment by MattIPv4** [comment]
Contributing and development are covered in the README: https://github.com/digitalocean/nginxconfig.io?tab=readme-ov-file#%EF%B8%8F-development

I don't think I'm worried about adding a code of conduct here for now.
