### ISSUE TITLE
Unable to redirect http to https . Can anyone help here ?

### ISSUE THREAD

**Issue by kaniket7209** [digitalocean/nginxconfig.io#428]
server {
    listen 80;
    server_name websocket.appeq.io;
    return 301 https://websocket.appeq.io$request_uri;
}
server{
    listen 443 ;
    server_name websocket.appeq.io;
    
    location /.well-known/acme-challenge/ {
        # HTTP-01 challenge
proxy_pass http://127.0.0.1:3050;
    }

    location / {
        proxy_pass http://127.0.0.1:3050;
        # Your web application
    } 
}

**Comment by MattIPv4** [comment]
👋 GitHub issues are meant to track bugs and feature requests with the NGINXConfig tool, not general support with NGINX configurations. I recommend posting on DigitalOcean's Q&A site if you need help: https://do.co/questions
