### ISSUE TITLE
Website Domain Redirection and WordPress Ecommerce Plan Purchase Error

### ISSUE THREAD

**Issue by tnawazzz** [digitalocean/nginxconfig.io#429]
Hey guys,

I don't know if it's the right place to discuss this but I am doing it anyway,

I need some help with my website, The Market Girl. Right now, it's hosted on the free plan WordPress and can be accessed at (http://www.themarketgirl.thebigshoutout.net/). But I want to redirect it to its actual Google domain, the-market-girl.co.uk.

Can you guys give me some guidance on how to do this? I want to make sure everything goes smoothly.

Also, I tried to buy the WordPress e-commerce plan but it didn't work out. I already reported the issue but no response.

Thanks a bunch for your time and support. Looking forward to hearing back from you soon!

**Comment by MattIPv4** [comment]
👋 This issue tracker is only meant for technical issues with the NGINXConfig tool itself. For help with configuring NGINX config generally, I recommend posting a question on DigitalOcean's community website: https://do.co/questions
