### ISSUE TITLE
Expect to add NJet configuration generation

### ISSUE THREAD

**Issue by TMLEngine** [digitalocean/nginxconfig.io#469]
NJet App Engine is a high-performance, lightweight WEB application and proxy software.As the data plane of the cloud native service mesh, NJet has many powerful functions such as dynamic configuration loading, active health detection, cluster high availability, declarative API, etc.

NJet fork nginx, compatible with the configuration of nginx. You can check out our code gallery.https://gitee.com/njet-rd

We see a lot of people using your configuration generation tools and looking to join NJet to increase our technical impact.
If you can join our research and development will actively cooperate.

Looking forward to your reply！

**Comment by MattIPv4** [comment]
I'm not quite sure what you're asking here?

**Comment by TMLEngine** [comment]
There is NGINXConfig on your website, our open source product NJet is a branch of nginx, I wonder if I can add NJet configuration generation to this page

**Comment by MattIPv4** [comment]
I do not think we have any plans to add support for additional web servers, be that forks of NGINX, or alternatives like Caddy or Apache. Sorry.

**Comment by TMLEngine** [comment]
Thank you for your reply, if one day you change your mind, you can contact me.
