### ISSUE TITLE
[Feature Request] NGINX conf optimized for docker deployment

### ISSUE THREAD

**Issue by Kiran-B** [digitalocean/nginxconfig.io#54]
NGINX publishes container images in Docker hub that includes default configuration and layout:
https://github.com/nginxinc/docker-nginx/tree/master/mainline/alpine

The default configuration of the containers differs in subtle ways; like `user` being `nginx`, `pid` being `/var/run/nginx.pid;` etc. I realize this tool provides sections to setup these values and thus match the values in container. However, I was wondering whether the tool could have out-of-the-box support for configuration to be put in the Docker container image. Perhaps a checkbox in 'Tools' section that indicates that deployment will be via Docker. If checked, the recommended configuration could be optimized for docker deployments.

**Comment by naviat** [comment]
+1 for Docker deployment

**Comment by ARKKYN** [comment]
+1 for Docker deployment

**Comment by MattIPv4** [comment]
This seems sensible to me, I'll add a button under the global docker section to apply these two tweaks 👍
