### ISSUE TITLE
[Feature Request] Content Security Policy

### ISSUE THREAD

**Issue by vipex** [digitalocean/nginxconfig.io#55]
Content security policy configurator and/or security level validator as in https://csp-evaluator.withgoogle.com/

Anyway the default policy is too insecure.

**Comment by mirorauhala** [comment]
This is a good idea, but in practice may be hard to implement.

I can't see a way where nginxconfig.io could easily add a CSP header that hardens the security without breaking sites.

**Comment by MattIPv4** [comment]
This tool is designed for configuring nginx itself -- adding dedicated configuration tooling for a single setting is really out of scope. There are many online tools and guides that already explain writing your own CSP header in detail, and nginx config lets you set whatever header you'd like for it. The default we provide is very open to ensure that it doesn't cause issues for users that are not familiar with CSP.
