### ISSUE TITLE
How to Add cloudflare FULL SSL 

### ISSUE THREAD

**Issue by bajpangosh** [digitalocean/nginxconfig.io#76]
I was trying to add cloudflare FULL SSL on wordpress, still getting ssl redirect loop, can you please add cloudflare ssl support?

**Comment by mirorauhala** [comment]
Are you sure wordpress isn't the one redirecting? I've managed a few wordpress sites and worpress itself tends to store the absolute URL into the database. You may need to change the URL from the wordpress settings.

As long as you have https set on your webserver using an CA-signed certificate, enabling Cloudflare FULL SSL should work right out of the box.
