### ISSUE TITLE
IPv6 DNS resolvers

### ISSUE THREAD

**Issue by miyurusankalpa** [digitalocean/nginxconfig.io#97]
Currently the DNS resolvers are IPv4 by default.

`resolver 1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 valid=60s;`

I think there should be a option for IPv6 DNS resolvers, as this configuration can lead to problems with IPv6 only servers.

Cloudflare IPv6

- 2606:4700:4700::1111
- 2606:4700:4700::1001

Google

- 2001:4860:4860::8888
- 2001:4860:4860::8844

OpenDNS

- 2620:119:35::35
- 2620:119:53::53

**Comment by 0xB4LINT** [comment]
Thank you @miyurusankalpa!
Now I think it's time to refactor the resolvers part (sorting, toggling, IPv6 handling).
I'll get back to you!
